
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;

/**
 * This class represents a GUI for a vending machine management system.
 * It allows users to create and test different types of vending machines.
 * @author Tiaro Molina
 * @author Bernardo Javier
 */
public class mainGUI extends javax.swing.JFrame {
    
    private static mainGUI instance; // Static instance variable
    private List<Denomination> availableDenominations;
    
    /**
     * This inner class represents a denomination in the vending machine.
     * Each denomination has a value and a count indicating the available quantity.
     */
    public class Denomination {
    private int value;
    private int count;

        /**
         * Constructs a denomination with the given value and count.
         *
         * @param value The value of the denomination.
         * @param count The initial count of the denomination.
         */
        public Denomination(int value, int count) {
        this.value = value;
        this.count = count;
    }

        /**
         *
         * @return
         */
        public int getValue() {
        return value;
    }

        /**
         *
         * @return
         */
        public int getCount() {
        return count;
    }

        /**
         *
         */
        public void decrementCount() {
        count--;
    }

        /**
         *
         * @param count
         */
        public void replenish(int count) {
        this.count += count;
    }
    }

    
    
    /**
     * Creates a new instance of the mainGUI class.
     * Initializes the available denominations for the vending machine.
     */
    public mainGUI() {
        initComponents();
        instance = this;
        initializeAvailableDenominations();
    }
    
    
    /**
     * Initializes the available denominations with their initial values and counts.
     */
    private void initializeAvailableDenominations() {
        availableDenominations = new ArrayList<Denomination>();
        availableDenominations.add(new Denomination(1000, 5)); // P1000
        availableDenominations.add(new Denomination(500, 5));  // P500
        availableDenominations.add(new Denomination(200, 5));  // P200
        availableDenominations.add(new Denomination(100, 5));  // P200
        
    }
    
     /**
     * Returns the an instance of the mainGUI class.
     *
     * @return The instance of the mainGUI class.
     */
    public static mainGUI getInstance() {
        return instance;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        butTest = new javax.swing.JButton();
        butExit = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        butCreate = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setIconImages(null);

        butTest.setText("Test a Vending Machine");
        butTest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butTestActionPerformed(evt);
            }
        });

        butExit.setText("Exit");
        butExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butExitActionPerformed(evt);
            }
        });

        jLabel1.setBackground(new java.awt.Color(51, 255, 204));
        jLabel1.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 1, 36)); // NOI18N
        jLabel1.setForeground(javax.swing.UIManager.getDefaults().getColor("Actions.Blue"));
        jLabel1.setText("Silog Vending Machine");

        butCreate.setText("Create Vending Machine");
        butCreate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butCreateActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(206, 206, 206)
                        .addComponent(butExit))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(162, 162, 162)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(butCreate)
                            .addComponent(butTest))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 83, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(74, 74, 74))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(jLabel1)
                .addGap(30, 30, 30)
                .addComponent(butCreate)
                .addGap(18, 18, 18)
                .addComponent(butTest)
                .addGap(18, 18, 18)
                .addComponent(butExit)
                .addContainerGap(90, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    boolean isRegular = true;
    
    /**
     *
     * @return
     */
    public boolean getIsregular(){
        return isRegular;
    }
    
    private void butExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butExitActionPerformed
        dispose();
    }//GEN-LAST:event_butExitActionPerformed

    private void butTestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butTestActionPerformed
         if(isRegular){
             regVendo regVending = new regVendo();
             regVending.show();
         } else if (!isRegular){
             specialVendo specVendo = new specialVendo();
             specVendo.show();
         }
    }//GEN-LAST:event_butTestActionPerformed

    
    
    private void butCreateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butCreateActionPerformed
         int choice = JOptionPane.showOptionDialog(
        this,
        "Select vending machine type:",
        "Select Vending Machine Type",
        JOptionPane.YES_NO_OPTION,
        JOptionPane.QUESTION_MESSAGE,
        null,
        new Object[]{"Regular", "Special"},
        null
    );
    
    if (choice == JOptionPane.YES_OPTION) {
        System.out.println("Regular is selected");
        isRegular = true;
    } else if (choice == JOptionPane.NO_OPTION) {
        System.out.println("Special is selected");
        isRegular = false;
    }
    System.out.println("IsRegular value: " + isRegular);

    }//GEN-LAST:event_butCreateActionPerformed

    /**
     * The main method to start the vending machine GUI application.
     *
     * @param args The command line arguments.
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(mainGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(mainGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(mainGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(mainGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new mainGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton butCreate;
    private javax.swing.JButton butExit;
    private javax.swing.JButton butTest;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
