/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */


public class regVendo extends javax.swing.JFrame {

    /**
     * Creates new form regVendo
     */
    public regVendo() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup2 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        butToc = new javax.swing.JRadioButton();
        butFri = new javax.swing.JRadioButton();
        butTapa = new javax.swing.JRadioButton();
        jRadioButton5 = new javax.swing.JRadioButton();
        butEgg = new javax.swing.JRadioButton();
        butHot = new javax.swing.JRadioButton();
        butCoke = new javax.swing.JRadioButton();
        butCor = new javax.swing.JRadioButton();
        butSpri = new javax.swing.JRadioButton();
        butOrder = new javax.swing.JButton();
        butretmain = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI Emoji", 1, 18)); // NOI18N
        jLabel1.setText("Regular Vending Machine");

        butToc.setText("Tocino (150 calories) - P300");
        butToc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butTocActionPerformed(evt);
            }
        });

        butFri.setText("Fried Rice (50 calories) - P100");
        butFri.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butFriActionPerformed(evt);
            }
        });

        butTapa.setText("Tapa (150 calories) - P300");
        butTapa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butTapaActionPerformed(evt);
            }
        });

        jRadioButton5.setText("jRadioButton5");

        butEgg.setText("Egg (10 calories) - P100");
        butEgg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butEggActionPerformed(evt);
            }
        });

        butHot.setText("Hotdog (150 calories) - P200");
        butHot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butHotActionPerformed(evt);
            }
        });

        butCoke.setText("Coke (100 calories) - P200");
        butCoke.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butCokeActionPerformed(evt);
            }
        });

        butCor.setText("Corned Beef (150 calories) - P200");
        butCor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butCorActionPerformed(evt);
            }
        });

        butSpri.setText("Sprite (100 calories) - P200");
        butSpri.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butSpriActionPerformed(evt);
            }
        });

        butOrder.setText("Order");
        butOrder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butOrderActionPerformed(evt);
            }
        });

        butretmain.setText("Main Menu");
        butretmain.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butretmainActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(butToc)
                            .addComponent(butTapa))
                        .addGap(53, 53, 53))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(butCor)
                            .addComponent(butHot))
                        .addGap(24, 24, 24)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(butCoke)
                    .addComponent(butSpri)
                    .addComponent(butEgg)
                    .addComponent(butFri))
                .addContainerGap(61, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(94, 94, 94)
                .addComponent(butOrder)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(butretmain)
                .addGap(102, 102, 102))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(153, 153, 153))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(215, Short.MAX_VALUE)
                    .addComponent(jRadioButton5)
                    .addContainerGap(208, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(jLabel1)
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(butFri)
                    .addComponent(butToc))
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(butEgg)
                    .addComponent(butTapa))
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(butCoke)
                    .addComponent(butHot))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(butCor)
                    .addComponent(butSpri))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(butOrder)
                    .addComponent(butretmain)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(157, Short.MAX_VALUE)
                    .addComponent(jRadioButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(179, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void butTapaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butTapaActionPerformed
        if(butTapa.isSelected()){
        butToc.setSelected(false);
        butHot.setSelected(false);
        butSpri.setSelected(false);
         butCoke.setSelected(false);
         butCor.setSelected(false);
         butFri.setSelected(false);
         butEgg.setSelected(false);}
         
    }//GEN-LAST:event_butTapaActionPerformed

    private void butretmainActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butretmainActionPerformed
        mainGUI.getInstance().setVisible(true); // Show the mainGUI instance
    dispose(); // Close the current window
    }//GEN-LAST:event_butretmainActionPerformed

    private void butOrderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butOrderActionPerformed
        // TODO add your handling code here:
        double price = 0; // for fried rice and egg
        double calories = 0;
        
        if (butToc.isSelected()) {
    price += 200;
    calories += 150;
} 
        if (butHot.isSelected()) {
    price += 200;
    calories += 150;
} 
        if (butCor.isSelected()) {
    price += 200;
    calories += 150;
} 
        if (butTapa.isSelected()) {
    price += 200;
    calories += 150;
} 
        if (butCoke.isSelected()) {
    price += 200;
    calories += 100;
} 
        if (butSpri.isSelected()) {
    price += 200;
    calories += 100;
} 
        
        if (butFri.isSelected()) {
    price += 100;
    calories += 50;
        }
        if (butEgg.isSelected()) {
    price += 100;
    calories += 10;
        }
        
 payment pay = new payment();

// Set text in t_Price and t_Cal fields
pay.getT_Price().setText(String.valueOf(price));
pay.getT_Cal().setText(String.valueOf(calories));
pay.show();
    }//GEN-LAST:event_butOrderActionPerformed

    private void butTocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butTocActionPerformed
        if(butToc.isSelected()){
        butTapa.setSelected(false);
        butHot.setSelected(false);
        butSpri.setSelected(false);
         butCoke.setSelected(false);
         butCor.setSelected(false);
         butFri.setSelected(false);
         butEgg.setSelected(false);}
    }//GEN-LAST:event_butTocActionPerformed

    private void butHotActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butHotActionPerformed
        if(butHot.isSelected()){
        butTapa.setSelected(false);
        butToc.setSelected(false);
        butSpri.setSelected(false);
         butCoke.setSelected(false);
         butCor.setSelected(false);
         butFri.setSelected(false);
         butEgg.setSelected(false);}
    }//GEN-LAST:event_butHotActionPerformed

    private void butCorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butCorActionPerformed
        if(butCor.isSelected()){
        butTapa.setSelected(false);
        butToc.setSelected(false);
        butSpri.setSelected(false);
         butCoke.setSelected(false);
         butHot.setSelected(false);
         butFri.setSelected(false);
         butEgg.setSelected(false);}
    }//GEN-LAST:event_butCorActionPerformed

    private void butFriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butFriActionPerformed
        if(butFri.isSelected()){
        butTapa.setSelected(false);
        butToc.setSelected(false);
        butSpri.setSelected(false);
         butCoke.setSelected(false);
         butCor.setSelected(false);
         butHot.setSelected(false);
         butEgg.setSelected(false);}
    }//GEN-LAST:event_butFriActionPerformed

    private void butEggActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butEggActionPerformed
        if(butEgg.isSelected()){
        butTapa.setSelected(false);
        butToc.setSelected(false);
        butSpri.setSelected(false);
         butCoke.setSelected(false);
         butCor.setSelected(false);
         butFri.setSelected(false);
         butHot.setSelected(false);}
    }//GEN-LAST:event_butEggActionPerformed

    private void butCokeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butCokeActionPerformed
        if(butCoke.isSelected()){
        butTapa.setSelected(false);
        butToc.setSelected(false);
        butSpri.setSelected(false);
         butHot.setSelected(false);
         butCor.setSelected(false);
         butFri.setSelected(false);
         butEgg.setSelected(false);}
    }//GEN-LAST:event_butCokeActionPerformed

    private void butSpriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butSpriActionPerformed
        if(butSpri.isSelected()){
        butTapa.setSelected(false);
        butToc.setSelected(false);
        butHot.setSelected(false);
         butCoke.setSelected(false);
         butCor.setSelected(false);
         butFri.setSelected(false);
         butEgg.setSelected(false);}
    }//GEN-LAST:event_butSpriActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(regVendo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(regVendo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(regVendo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(regVendo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new regVendo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton butCoke;
    private javax.swing.JRadioButton butCor;
    private javax.swing.JRadioButton butEgg;
    private javax.swing.JRadioButton butFri;
    private javax.swing.JRadioButton butHot;
    private javax.swing.JButton butOrder;
    private javax.swing.JRadioButton butSpri;
    private javax.swing.JRadioButton butTapa;
    private javax.swing.JRadioButton butToc;
    private javax.swing.JButton butretmain;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JRadioButton jRadioButton5;
    // End of variables declaration//GEN-END:variables
}
